# Generated by Django 4.1.1 on 2022-10-02 13:03

from django.db import migrations, models
import django.db.models.deletion
import pulsar_test.products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('article', models.CharField(max_length=255, unique=True, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Цена')),
                ('status', models.IntegerField(choices=[(0, 'Без статуса'), (1, 'В наличии'), (2, 'Под заказ'), (3, 'Ожидается поступление'), (4, 'Нет в наличии'), (5, 'Не производится')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=pulsar_test.products.models.ProductImage.image_dir, verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображение',
                'ordering': ('created_at',),
            },
        ),
    ]
